[package]
name = "physeter"
version = "0.1.0"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
edition = "2018"

[profile.release]
overflow-checks = true
panic = "abort"
opt-level = 3
debug = true
lto = true

[dependencies]
rocksdb = "0.15.0"
bytes = "0.5.4"
anyhow = "1.0"